#ifndef __AST_NODE_TYPES_H__
#define __AST_NODE_TYPES_H__
enum AST_NODE_TYPES{
    EXPR, LITERAL, GROUPING, UNARY, BINARY, VARIABLE, ASSIGN, EXPR_SUPER,
    EXPR_LOGICAL, EXPR_FUNC_CALL, EXPR_INST_GET, EXPR_INST_SET, EXPR_THIS,
    STMT, STMT_EXPRESSION, STMT_PRINT, STMT_VAR, STMT_BLOCK,
    STMT_IF, STMT_WHILE, STMT_FOR, STMT_RET,
    DEFN_FUNC, DEFN_CLASS
};
#endif