#ifndef __AST_NODE_TYPES_H__
#define __AST_NODE_TYPES_H__
enum AST_NODE_TYPES{
    EXPR, LITERAL, GROUPING, UNARY, BINARY, VARIABLE, ASSIGN,
    STMT, STMT_EXPRESSION, STMT_PRINT, STMT_VAR, STMT_BLOCK
};
#endif